export const levelCoreRecipes: string[][] = [
  [
    "poisonous_chainmail",
    "tome_of_the_past",
    "gauntlet_of_greats",
    "fury",
    "breath_of_fire",
  ],
  ["staff_of_fauna", "topaz", "essence_of_the_forest"],
  ["new_year_hat", "parasite", "ominous_shield", "corruption", "vampire_fang"],
  [
    "fire_orb",
    "wild_worm",
    "talisman_of_protection",
    "talisman_of_health",
    "crystal_ball",
  ],
  ["rune_axe", "opal", "ice_shard"],
  ["creator_set_activator", "cube_opal", "bloody_diadem_emerald"],
  [
    "power_of_corruption",
    "power_of_darkness",
    "life_steal",
    "dark_power",
    "plague_energy",
  ],
  ["dark_flame_chainmail", "emerald", "essence_of_darkness"],
  [
    "rosehip",
    "knight_chestplate",
    "flesh_ripper",
    "emerald_duplicate",
    "essence_of_dark_rider",
  ],
  [
    "death_blocker",
    "kaya_armor",
    "naga_headwear",
    "medusa_necklace",
    "essence_of_abyss",
  ],
  [
    "accuracy_above_all",
    "spear_of_moonlight",
    "elves_cloak",
    "skull_of_the_dead",
    "staff_of_the_dead",
  ],
  ["knight_move", "essence_of_the_sea"],
  ["golden", "staff_of_darkness", "shards", "kyanite", "essence_of_earth"],
  ["book_of_strength", "book_of_agility", "book_of_wisdom", "essence_of_stone"],
  ["treasure_map", "rune_of_fever", "box_of_gold", "broken_scythe"],
  ["dark_claw_of_prime", "bloodstained_claw"],
  ["phoenix", "only_in_dreams", "soul_ache", "essence_of_crustacean"],
  [
    "armor_of_frost",
    "rotten_carcass",
    "brightness_3",
    "flight_of_thought_3",
    "burst_of_rage_3",
  ],
  ["dark_grimoire", "cursed_whirlwind", "amulet_of_vengeance"],
  [
    "soul_of_destroyer_in_blood",
    "soul_of_spider_in_blood",
    "soul_of_xeron_in_blood",
  ],
  ["essence_of_warrior_po", "essence_of_thief_po", "essence_of_mage_po"],
  ["cursed_amulet_es", "magical_amulet_es", "soul_of_uzuran_in_blood"],
  ["courier_marquis", "courier_kai", "smiling_apple"],
  ["dark_unity", "essence_of_sand"],
  [
    "poisonous_rune_of_strength",
    "poisonous_rune_of_agility",
    "poisonous_rune_of_wisdom",
  ],
  ["introduction_to_absolute", "soul_of_kai_in_blood"],
  ["soul_of_mother", "soul_of_kropus"],
  ["sandy_trail", "sand_storm", "sand_spiral"],
  ["cursed_unity", "soul_of_marquis_in_blood"],
];
